# Generated by Django 3.0.2 on 2020-03-06 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0002_auto_20200306_2039'),
        ('keyboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='switch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='switches.Switch'),
        ),
    ]
