# Generated by Django 3.0.2 on 2020-03-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboards', '0002_keyboard_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
