# Generated by Django 3.0.2 on 2020-03-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboards', '0003_auto_20200306_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='description',
            field=models.TextField(max_length=90),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
