# Generated by Django 3.0.2 on 2020-03-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0002_auto_20200306_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
